export type Nivel = 'Administrador' | 'Cliente'
export interface Usuario { id: string; nome: string; email: string; telefone?: string | null; dataNascimento?: string | null; nivel: Nivel; ativo?: boolean; provedorAuth?: string; cadastroConcluido?: boolean; fotoUrl?: string | null }
export interface Servico { id: string; nome: string; descricao?: string | null; preco: number; duracao: number; ativo: boolean }
export interface Profissional { id: string; nome: string; telefone?: string | null; email?: string | null; especialidade?: string | null; ativo: boolean }
export interface Agendamento { id: string; data: string; hora: string; status: string; observacao?: string | null; usuario?: Usuario; profissional?: Profissional; servico?: Servico }
export interface RegrasAgendamento { antecedenciaCancelamentoHoras: number; antecedenciaRemarcacaoHoras: number; toleranciaAtrasoMinutos: number }
export interface EvolutionStatus { configurada: boolean; disponivel: boolean; instanciaCriada: boolean; conectada: boolean; instancia: string | null; nomeExibicao: string | null; estado: string | null; mensagem?: string }
export interface ModelosMensagemWhatsApp { criacao: string; remarcacao: string; cancelamento: string; atualizacao: string; pendente: string; confirmado: string; concluido: string; atrasado: string }
export interface RegrasEnvioAutomatico { criacao: boolean; remarcacao: boolean; cancelamento: boolean; pendente: boolean; confirmado: boolean; concluido: boolean; atrasado: boolean; lembrete: boolean; antecedenciaLembreteMinutos: number }
export type DisponibilidadeFuncionario = Record<number, string[]>

const API_BASE_URL = import.meta.env.VITE_API_URL || '/api'
const tokenKey = 'barbearia.token'
export const authStorage = { get: () => localStorage.getItem(tokenKey), set: (token: string) => localStorage.setItem(tokenKey, token), clear: () => localStorage.removeItem(tokenKey) }

async function request<T>(path: string, options: RequestInit = {}): Promise<T> {
  const response = await fetch(`${API_BASE_URL}${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(authStorage.get() ? { Authorization: `Bearer ${authStorage.get()}` } : {}), ...options.headers } })
  const data = await response.json().catch(() => ({}))
  if (!response.ok) throw new Error(data.error || 'Não foi possível concluir a solicitação.')
  return data as T
}
const body = (method: string, value?: unknown) => ({ method, body: value === undefined ? undefined : JSON.stringify(value) })
export const api = {
  auth: { login: (value: { email: string; password: string }) => request<{ token: string; user: Usuario }>('/auth/login', body('POST', value)), register: (value: { nome: string; email: string; password: string; telefone?: string }) => request<{ token: string; user: Usuario }>('/auth/register', body('POST', value)), google: (idToken: string) => request<{ token: string; user: Usuario }>('/auth/google', body('POST', { idToken })) },
  usuarios: { me: () => request<Usuario>('/usuarios/me'), updateMe: (value: Partial<Usuario>) => request<Usuario>('/usuarios/me', body('PUT', value)), concluirCadastro: (value: { nome: string; telefone: string }) => request<Usuario>('/usuarios/me/concluir-cadastro', body('PUT', value)), excluirMinhaConta: (confirmacao: string) => request<{ success: true }>('/usuarios/me', body('DELETE', { confirmacao })), list: () => request<Usuario[]>('/usuarios'), create: (value: Partial<Usuario> & { senha?: string }) => request<Usuario>('/usuarios', body('POST', value)), update: (id: string, value: Partial<Usuario>) => request<Usuario>(`/usuarios/${id}`, body('PUT', value)), remove: (id: string) => request(`/usuarios/${id}`, body('DELETE')) },
  servicos: { list: () => request<Servico[]>('/servicos'), create: (value: Partial<Servico>) => request<Servico>('/servicos', body('POST', value)), update: (id: string, value: Partial<Servico>) => request<Servico>(`/servicos/${id}`, body('PUT', value)), remove: (id: string) => request(`/servicos/${id}`, body('DELETE')) },
  profissionais: { list: () => request<Profissional[]>('/profissionais'), listAdmin: () => request<Profissional[]>('/profissionais/admin'), create: (value: Pick<Profissional, 'nome' | 'telefone' | 'email' | 'ativo'>) => request<Profissional>('/profissionais', body('POST', value)), update: (id: string, value: Pick<Profissional, 'nome' | 'telefone' | 'email' | 'ativo'>) => request<Profissional>(`/profissionais/${id}`, body('PUT', value)), remove: (id: string) => request<Profissional>(`/profissionais/${id}`, body('DELETE')), disponibilidade: (id: string) => request<DisponibilidadeFuncionario>(`/profissionais/${id}/disponibilidade`), salvarDisponibilidade: (id: string, disponibilidade: DisponibilidadeFuncionario) => request<{ ok: boolean }>(`/profissionais/${id}/disponibilidade`, body('PUT', { disponibilidade })) },
  agendamentos: { list: () => request<Agendamento[]>('/agendamentos'), create: (value: { usuarioId?: string; profissionalId: string; servicoId: string; data: string; hora: string; observacao?: string }) => request<Agendamento>('/agendamentos', body('POST', value)), update: (id: string, value: Partial<{ profissionalId: string; servicoId: string; data: string; hora: string; status: string; observacao: string }>) => request<Agendamento>(`/agendamentos/${id}`, body('PUT', value)), remove: (id: string) => request<void>(`/agendamentos/${id}`, body('DELETE')), cancel: (id: string) => request<Agendamento>(`/agendamentos/${id}/cancelar`, body('PATCH')), remarcar: (id: string, value: { data: string; hora: string; profissionalId?: string; servicoId?: string }) => request<Agendamento>(`/agendamentos/${id}/remarcar`, body('PATCH', value)), historico: (id: string) => request<Array<{ id: string; tipo: string; createdAt: string }>>(`/agendamentos/${id}/historico`), status: (id: string, status: string) => request<Agendamento>(`/agendamentos/${id}/status`, body('PATCH', { status })), notificar: (id: string, tipo: 'CRIACAO' | 'REMARCACAO' | 'CANCELAMENTO' | 'ATUALIZACAO' | 'PENDENTE' | 'CONFIRMADO' | 'CONCLUIDO' | 'ATRASADO') => request<{ ok: true }>(`/agendamentos/${id}/notificar`, body('POST', { tipo })), disponibilidade: (profissionalId: string, servicoId: string, data: string, ignorarAgendamentoId?: string) => { const query = new URLSearchParams({ profissionalId, servicoId, data }); if (ignorarAgendamentoId) query.set('ignorarAgendamentoId', ignorarAgendamentoId); return request<{ horarios: string[] }>(`/agendamentos/disponibilidade?${query}`) } },
  configuracoes: { publico: () => request<{ telefoneWhatsApp: string | null; email: string | null; instagram: string | null }>('/configuracoes-publicas'), get: () => request<{ telefoneWhatsApp?: string | null; email?: string | null; instagram?: string | null }>('/configuracoes'), update: (value: { telefoneWhatsApp: string; email: string; instagram: string }) => request('/configuracoes', body('PUT', value)), regras: () => request<RegrasAgendamento>('/configuracoes/regras'), salvarRegras: (value: RegrasAgendamento) => request<RegrasAgendamento>('/configuracoes/regras', body('PUT', value)) },
  evolution: { status: () => request<EvolutionStatus>('/integracoes/evolution/status'), criarInstancia: () => request<{ base64?: string; pairingCode?: string | null }>('/integracoes/evolution/instancia', body('POST')), conectar: () => request<{ base64?: string; pairingCode?: string | null }>('/integracoes/evolution/conectar', body('POST')), reconectar: () => request<{ base64?: string; pairingCode?: string | null }>('/integracoes/evolution/reconectar', body('POST')), desconectar: () => request('/integracoes/evolution/desconectar', body('POST')), excluirInstancia: () => request('/integracoes/evolution/instancia', { method: 'DELETE' }), atualizarNomeExibicao: (nome: string) => request('/integracoes/evolution/nome-exibicao', body('PUT', { nome })), mensagens: () => request<ModelosMensagemWhatsApp>('/integracoes/evolution/mensagens'), salvarMensagens: (value: ModelosMensagemWhatsApp) => request<ModelosMensagemWhatsApp>('/integracoes/evolution/mensagens', body('PUT', value)), envioAutomatico: () => request<{ ativo: boolean }>('/integracoes/evolution/envio-automatico'), salvarEnvioAutomatico: (ativo: boolean) => request<{ ativo: boolean }>('/integracoes/evolution/envio-automatico', body('PUT', { ativo })), regrasEnvioAutomatico: () => request<{ ativo: boolean; regras: RegrasEnvioAutomatico }>('/integracoes/evolution/regras-envio-automatico'), salvarRegrasEnvioAutomatico: (value: RegrasEnvioAutomatico) => request<{ ativo: boolean; regras: RegrasEnvioAutomatico }>('/integracoes/evolution/regras-envio-automatico', body('PUT', value)) }
}
