import { Route, Switch } from 'wouter'
import { Toaster } from 'react-hot-toast'
import { AuthProvider } from '@/contexts/AuthContext'
import { AdminRoute, UserRoute } from '@/components/ProtectedRoute'
import HomePage from '@/pages/HomePage'
import LoginPage from '@/pages/LoginPage'
import AgendarPage from '@/pages/agendar/AgendarPage'
import PainelPage from '@/pages/PainelPage'
import MinhaContaPage from '@/pages/user/MinhaContaPage'
export default function App() { return <AuthProvider><Toaster position="top-right" /><Switch><Route path="/" component={HomePage} /><Route path="/login" component={LoginPage} /><Route path="/agendamento" component={AgendarPage} /><Route path="/painel/:rest*" component={() => <AdminRoute component={PainelPage} />} /><Route path="/painel" component={() => <AdminRoute component={PainelPage} />} /><Route path="/minha-conta" component={() => <UserRoute component={MinhaContaPage} />} /><Route>Não encontrado.</Route></Switch></AuthProvider> }
