'use client'
import { useEffect, useState } from 'react'
import { Button } from '@/components/ui/button'
import { Modal } from '@/components/ui/modal'

type Field = { key: string; label: string; type?: 'text' | 'number' | 'email'; required?: boolean }
type Item = { id: string; ativo: boolean; [key: string]: unknown }
export function CrudPage({ title, endpoint, fields }: { title: string; endpoint: string; fields: Field[] }) {
  const [items, setItems] = useState<Item[]>([]); const [search, setSearch] = useState(''); const [loading, setLoading] = useState(true); const [message, setMessage] = useState(''); const [editing, setEditing] = useState<Item | null>(null); const [confirming, setConfirming] = useState<Item | null>(null)
  const load = async () => { setLoading(true); try { const response = await fetch(`${endpoint}?search=${encodeURIComponent(search)}`); const data = await response.json(); if (!response.ok) throw new Error(data.error); setItems(data.items) } catch (error) { setMessage(error instanceof Error ? error.message : 'Não foi possível carregar os dados.') } finally { setLoading(false) } }
  useEffect(() => { void load() }, [search])
  const save = async (form: FormData) => { const data: Record<string, unknown> = Object.fromEntries(form); data.ativo = form.get('ativo') === 'on'; const response = await fetch(editing?.id ? `${endpoint}/${editing.id}` : endpoint, { method: editing?.id ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setMessage('Dados salvos com sucesso.'); setEditing(null); await load() }
  const remove = async () => { if (!confirming) return; const response = await fetch(`${endpoint}/${confirming.id}`, { method: 'DELETE' }); const result = await response.json(); if (!response.ok) { setMessage(result.error); setConfirming(null); return }; setMessage('Registro excluído com sucesso.'); setConfirming(null); await load() }
  return <section className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><h1 className="text-2xl font-bold">{title}</h1><Button onClick={() => setEditing({ id: '', ativo: true })}>Cadastrar</Button></div><input className="w-full rounded-lg border p-2" aria-label={`Pesquisar ${title}`} placeholder="Pesquisar por nome" value={search} onChange={event => setSearch(event.target.value)} />{message && <p role="status" className="rounded bg-slate-100 p-3 text-sm">{message}</p>}<div className="overflow-x-auto rounded-xl bg-white shadow"><table className="w-full text-left text-sm"><thead><tr className="border-b">{fields.map(field => <th className="p-3" key={field.key}>{field.label}</th>)}<th className="p-3">Status</th><th className="p-3">Ações</th></tr></thead><tbody>{loading ? <tr><td className="p-4" colSpan={fields.length + 2}>Carregando...</td></tr> : items.length ? items.map(item => <tr className="border-b" key={item.id}>{fields.map(field => <td className="p-3" key={field.key}>{String(item[field.key] ?? '—')}</td>)}<td className="p-3">{item.ativo ? 'Ativo' : 'Inativo'}</td><td className="flex gap-2 p-3"><button className="text-blue-700" onClick={() => setEditing(item)}>Editar</button><button className="text-red-700" onClick={() => setConfirming(item)}>Excluir</button></td></tr>) : <tr><td className="p-4" colSpan={fields.length + 2}>Nenhum registro encontrado.</td></tr>}</tbody></table></div>{editing && <Modal title={editing.id ? `Editar ${title.slice(0, -1)}` : `Cadastrar ${title.slice(0, -1)}`} onClose={() => setEditing(null)}><form className="space-y-3" action={async form => { try { await save(form) } catch (error) { setMessage(error instanceof Error ? error.message : 'Não foi possível salvar.') } }}>{fields.map(field => <label className="block" key={field.key}>{field.label}<input className="mt-1 w-full rounded border p-2" name={field.key} type={field.type ?? 'text'} required={field.required} defaultValue={String(editing[field.key] ?? '')} /></label>)}<label className="flex gap-2"><input name="ativo" type="checkbox" defaultChecked={editing.ativo} />Ativo</label><Button type="submit">Salvar</Button></form></Modal>}{confirming && <Modal title="Confirmar exclusão" onClose={() => setConfirming(null)}><p>Tem certeza que deseja excluir este profissional?</p><div className="mt-5 flex justify-end gap-2"><Button className="bg-slate-500" onClick={() => setConfirming(null)}>Cancelar</Button><Button className="bg-red-700" onClick={remove}>Excluir</Button></div></Modal>}</section>
}
