import { useEffect, useState, type FormEvent } from 'react'
import toast from 'react-hot-toast'
import { api } from '@/lib/api'
import { formatarTelefoneBrasileiro } from '@/utils/telefone'

export default function WhatsAppConfigPage() {
  const [form, setForm] = useState({ telefoneWhatsApp: '', email: '', instagram: '' })
  useEffect(() => { void api.configuracoes.get().then(config => setForm({ telefoneWhatsApp: formatarTelefoneBrasileiro(config.telefoneWhatsApp ?? ''), email: config.email ?? '', instagram: config.instagram ?? '' })).catch(error => toast.error(error.message)) }, [])
  const save = async (event: FormEvent) => { event.preventDefault(); try { await api.configuracoes.update(form); toast.success('Dados de contato atualizados.') } catch (error) { toast.error(error instanceof Error ? error.message : 'Não foi possível salvar.') } }
  return <section className="mx-auto max-w-xl"><h1 className="text-2xl font-bold text-slate-950">Configurações</h1><p className="mt-1 text-slate-600">Defina os contatos e redes sociais exibidos no site.</p><form onSubmit={save} className="mt-6 space-y-5 rounded-lg border border-slate-200 bg-white p-6 shadow-sm"><label className="block text-sm font-semibold text-slate-800">WhatsApp da barbearia<input required inputMode="tel" maxLength={15} className="input-field mt-1" placeholder="(00) 00000-0000" value={form.telefoneWhatsApp} onChange={event => setForm(current => ({ ...current, telefoneWhatsApp: formatarTelefoneBrasileiro(event.target.value) }))} /></label><label className="block text-sm font-semibold text-slate-800">E-mail de contato<input required type="email" className="input-field mt-1" placeholder="contato@barbearia.com" value={form.email} onChange={event => setForm(current => ({ ...current, email: event.target.value }))} /></label><label className="block text-sm font-semibold text-slate-800">Instagram<input className="input-field mt-1" placeholder="https://instagram.com/sua-barbearia" value={form.instagram} onChange={event => setForm(current => ({ ...current, instagram: event.target.value }))} /><span className="mt-1 block text-xs font-normal text-slate-500">Informe o link completo do perfil.</span></label><button className="btn-primary">Salvar contatos</button></form></section>
}
